name: lab01

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - run: sudo apt-get install pandoc inkscape
      - uses: actions/checkout@v4
      - run: python -m nbconvert lab1/pint_and_boiling_point.ipynb --to pdf

