name: lab01

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: python -m nbconvert lab1/pint_and_boiling_point.ipynb --to pdf --execute
      - uses: actions/upload-artifact@v4
        with:
          path: lab1/pint_and_boiling_point.pdf

