name: lab01


on: 
  push:
    paths:
      - 'lab1/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: pip install -r requirements.txt
      - run: python -m nbconvert lab1/pint_and_boiling_point.ipynb --to pdf --execute
      - uses: actions/upload-artifact@v4
        with:
          name: pint_and_boiling_point.pdf
          path: lab1/pint_and_boiling_point.pdf
