name: lab3

on: 
  push:
    paths:
      - 'lab3/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: pip install -r requirements.txt
      - run: python -m nbconvert lab3/lab3.ipynb --to pdf --execute
      - uses: actions/upload-artifact@v4
        with:
          name: lab3.pdf
          path: lab3/lab3.pdf

