name: lab6

on:
  push:
    paths:
      - "lab6/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: pip install -r requirements.txt
      - run: python -m nbconvert lab6/lab6.ipynb --to pdf --execute
      - uses: actions/upload-artifact@v4
        with:
          name: lab6.pdf
          path: lab6/lab6.pdf
